<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DocumentFormat.OpenXml">
      <HintPath>..\..\DocumentFormat.OpenXml.dll</HintPath>
    </Reference>
    <Reference Include="DocumentFormat.OpenXml.Framework">
      <HintPath>..\..\DocumentFormat.OpenXml.Framework.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Packaging">
      <HintPath>..\..\System.IO.Packaging.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
