<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ClosedXML">
      <HintPath>..\..\ClosedXML.dll</HintPath>
    </Reference>
    <Reference Include="DocumentFormat.OpenXml">
      <HintPath>..\..\DocumentFormat.OpenXml.dll</HintPath>
    </Reference>
    <Reference Include="ExcelNumberFormat">
      <HintPath>..\..\ExcelNumberFormat.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
