using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using AspNetCoreGeneratedDocument;
using Microsoft.AspNetCore.Mvc.ApplicationParts;
using Microsoft.AspNetCore.Razor.Hosting;

[assembly: AssemblyCompany("AxiomaReporting.Web")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0+fa9516354312c822c73cd54d591f337cda163d11")]
[assembly: AssemblyProduct("AxiomaReporting.Web")]
[assembly: AssemblyTitle("AxiomaReporting.Web")]
[assembly: InternalsVisibleTo("AxiomaReporting.Tests")]
[assembly: ApplicationPart("FluentValidation.AspNetCore")]
[assembly: ProvideApplicationPartFactory("Microsoft.AspNetCore.Mvc.ApplicationParts.ConsolidatedAssemblyApplicationPartFactory, Microsoft.AspNetCore.Mvc.Razor")]
[assembly: RazorCompiledItem(typeof(Views_Allocations_Create), "mvc.1.0.view", "/Views/Allocations/Create.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Account_AccessDenied), "mvc.1.0.view", "/Views/Account/AccessDenied.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Account_ChangePassword), "mvc.1.0.view", "/Views/Account/ChangePassword.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Account_ForgotPassword), "mvc.1.0.view", "/Views/Account/ForgotPassword.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Account_Login), "mvc.1.0.view", "/Views/Account/Login.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Account_ResetPassword), "mvc.1.0.view", "/Views/Account/ResetPassword.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Account_TermsOfUse), "mvc.1.0.view", "/Views/Account/TermsOfUse.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Account_TwoFactor), "mvc.1.0.view", "/Views/Account/TwoFactor.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_AuditLog), "mvc.1.0.view", "/Views/Admin/AuditLog.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_BatchReportImport), "mvc.1.0.view", "/Views/Admin/BatchReportImport.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_BatchReportImportResult), "mvc.1.0.view", "/Views/Admin/BatchReportImportResult.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_Branding), "mvc.1.0.view", "/Views/Admin/Branding.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_DataMigration), "mvc.1.0.view", "/Views/Admin/DataMigration.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_EditReportingMonth), "mvc.1.0.view", "/Views/Admin/EditReportingMonth.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_EmailServerSettings), "mvc.1.0.view", "/Views/Admin/EmailServerSettings.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_EmailTemplates), "mvc.1.0.view", "/Views/Admin/EmailTemplates.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_Frameworks), "mvc.1.0.view", "/Views/Admin/Frameworks.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_InspectorAssignments), "mvc.1.0.view", "/Views/Admin/InspectorAssignments.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_Institutions), "mvc.1.0.view", "/Views/Admin/Institutions.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_NotificationLogs), "mvc.1.0.view", "/Views/Admin/NotificationLogs.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_ProjectPrograms), "mvc.1.0.view", "/Views/Admin/ProjectPrograms.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_ReportingMonths), "mvc.1.0.view", "/Views/Admin/ReportingMonths.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_SystemConstants), "mvc.1.0.view", "/Views/Admin/SystemConstants.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin_TermsOfUse), "mvc.1.0.view", "/Views/Admin/TermsOfUse.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Admin__NotificationLogDetails), "mvc.1.0.view", "/Views/Admin/_NotificationLogDetails.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Dashboard_Index), "mvc.1.0.view", "/Views/Dashboard/Index.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Dashboard_Summary), "mvc.1.0.view", "/Views/Dashboard/Summary.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Employee_AllocationForm), "mvc.1.0.view", "/Views/Employee/AllocationForm.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Employee_AllocationList), "mvc.1.0.view", "/Views/Employee/AllocationList.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Employee_Allocations), "mvc.1.0.view", "/Views/Employee/Allocations.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Employee_Form), "mvc.1.0.view", "/Views/Employee/Form.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Employee_Index), "mvc.1.0.view", "/Views/Employee/Index.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Home_Index), "mvc.1.0.view", "/Views/Home/Index.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Home_Privacy), "mvc.1.0.view", "/Views/Home/Privacy.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Lookup_Index), "mvc.1.0.view", "/Views/Lookup/Index.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Lookup_List), "mvc.1.0.view", "/Views/Lookup/List.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_MyAllocations_Details), "mvc.1.0.view", "/Views/MyAllocations/Details.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_MyAllocations_Index), "mvc.1.0.view", "/Views/MyAllocations/Index.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Report_Index), "mvc.1.0.view", "/Views/Report/Index.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Report_Manual), "mvc.1.0.view", "/Views/Report/Manual.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Report_NoActiveMonth), "mvc.1.0.view", "/Views/Report/NoActiveMonth.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Report_NoAllocation), "mvc.1.0.view", "/Views/Report/NoAllocation.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Report_SelectAllocation), "mvc.1.0.view", "/Views/Report/SelectAllocation.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Shared_Components_SiteLogo_Default), "mvc.1.0.view", "/Views/Shared/Components/SiteLogo/Default.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Shared_Error), "mvc.1.0.view", "/Views/Shared/Error.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Shared__AnonymousLayout), "mvc.1.0.view", "/Views/Shared/_AnonymousLayout.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Shared__ValidationScriptsPartial), "mvc.1.0.view", "/Views/Shared/_ValidationScriptsPartial.cshtml")]
[assembly: RazorCompiledItem(typeof(Views__ViewImports), "mvc.1.0.view", "/Views/_ViewImports.cshtml")]
[assembly: RazorCompiledItem(typeof(Views__ViewStart), "mvc.1.0.view", "/Views/_ViewStart.cshtml")]
[assembly: RazorCompiledItem(typeof(Views_Shared__Layout), "mvc.1.0.view", "/Views/Shared/_Layout.cshtml")]
[assembly: AssemblyVersion("1.0.0.0")]
